spring:
  profiles:
#    include: jwt, oauth, local
    include: docker

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
      enabled: true

logging.level:
  org.hibernate.SQL: debug

file:
  base-dir: /

naver:
  client-id: ${NAVER_CLIENT_ID}
  secret: ${NAVER_SECRET}

#  # security logging
#  org.springframework.security: DEBUG